version: '3'
tasks:
  list:
    default: true
    desc: List all available tasks
    cmds:
      - task --list
  buildlinux:
    desc: Build the project for Linux AMD64
    sources:
      - '**/*.go'
      - go.mod
    exclude:
      - '**/*_test.go'
    method: timestamp
    cmds:
      - GOOS=linux GOARCH=amd64 GIN_MODE=release go build -o ./eneb .
    generates:
      - ./eneb

  buildwindows:
    desc: Build the project for Windows AMD64
    sources:
      - '**/*.go'
      - go.mod
    exclude:
      - '**/*_test.go'
    method: timestamp
    cmds:
      - GOOS=windows GOARCH=amd64 GIN_MODE=release go build -o ./eneb.exe .
    generates:
      - ./eneb.exe
